name: Run Ansible tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.9"
          - "3.8"

    defaults:
      run:
        working-directory: ansible_collections/

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ansible_collections/ansible/eda

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package dependencies
        run: |
          sudo apt-get update
          sudo apt-get --assume-yes --no-install-recommends install libsystemd0 libsystemd-dev pkg-config

      - name: Install ansible and wheel
        run: python -m pip install ansible wheel

      - name: Run sanity tests
        run: ansible-test sanity
        working-directory: ansible_collections/ansible/eda

      - name: Run unit tests
        run: ansible-test units --venv
        working-directory: ansible_collections/ansible/eda
